#!/usr/local/bin/python
# -*- coding: utf-8 -*-
# kate: space-indent on; indent-width 4; mixedindent off; indent-mode python;

from __future__ import print_function
import sys
import os
import ConfigParser

filename = None
input_file = None
section = None
verbose = int(os.getenv('GUNICORN_DEBUG', '0')) != 0

if len(sys.argv) == 5:
    filename = sys.argv[1]
    section = sys.argv[2]
    key = sys.argv[3]
    value = sys.argv[4]
elif len(sys.argv) == 3:
    filename = sys.argv[1]
    input_file = sys.argv[2]
else:
    print("Invalid arguments.", file=sys.stderr)
    sys.exit(1)

if filename is None:
    print("No filename specified.", file=sys.stderr)
    sys.exit(2)
else:
    f = open(filename, 'r')
    ini = ConfigParser.ConfigParser()
    ini.readfp(f)
    f.close()

if section is not None:
    if not ini.has_section(section):
        ini.add_section(section)
    ini.set(section, key, value)

if input_file is not None:
    f = open(input_file, 'r')
    for line in f.readlines():
        line = line.strip()
        if not line:
            continue
        if line[0] == '#':
            continue
        if line.startswith('set:'):
            line = line[4:]
            key, value = line.split('=', 1)
            if '/' in key:
                section, key = key.split('/', 1)
            else:
                section = None
            if not ini.has_section(section):
                ini.add_section(section)
            if verbose:
                print('set [%s]/%s=%s' % (section, key, value))
            ini.set(section, key, value)
        elif line.startswith('delete:'):
            line = line[7:]
            if '/' in line:
                section, key = line.split('/', 1)
            else:
                section = line
                key = None
            if key:
                if verbose:
                    print('delete [%s]/%s' % (section, key))
                if ini.has_section(section):
                    ini.remove_option(section, key)
            else:
                if verbose:
                    print('delete [%s]' % (section))
                if ini.has_section(section):
                    ini.remove_section(section)
        elif line.startswith('clear:'):
            section = line[6:]
            if verbose:
                print('clear [%s]' % (section))
            if ini.has_section(section):
                ini.remove_section(section)
            ini.add_section(section)
        else:
            print('Unknown command line: %s' % line)

    f.close()

if filename is not None:
    f = open(filename, 'w')
    ini.write(f)
    f.close()

sys.exit(0)
