#!/bin/sh
script_file=`readlink -f "$0"`
script_dir=`dirname "$script_file"`

trac_env='/home/trac/env'
trac_backup_dir='/home/trac/backup'

backup_id=`date "+%Y-%m-%d_%H:%M:%S"`

/bin/trac-admin "$trac_env" hotcopy "$trac_backup_dir/$backup_id"
